name: vecTrade1
channels:
  - conda-forge
  - defaults
dependencies:
  # Python版本
  - python=3.9
  
  # 科学计算
  - numpy=1.24.3
  - scipy=1.10.1
  - pandas=2.0.3
  
  # 可视化
  - matplotlib=3.7.2
  - seaborn=0.12.2
  
  # 机器学习
  - scikit-learn=1.3.0
  
  # Jupyter环境
  - jupyter
  - notebook
  - ipykernel
  
  # 系统工具
  - pip
  
  # pip依赖
  - pip:
    # 向量数据库
    - hnswlib==0.7.0
    
    # 进度条和工具
    - tqdm==4.65.0
    
    # 高级可视化（可选）
    - plotly==5.15.0
    
    # 实验管理（可选）
    - tensorboard==2.13.0
    - mlflow==2.5.0
    
    # 大规模数据处理（可选）
    - h5py==3.9.0
    
    # 性能分析（可选）
    - memory-profiler==0.61.0
    - line-profiler==4.0.3